services:
  - type: web
    name: speak-note-backend
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port 8000
    branch: main
    autoDeploy: true 