"""add timezone column to reminders

Revision ID: acadce3c11e3
Revises: 0be4d6715397
Create Date: 2025-06-19 13:01:29.933721

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'acadce3c11e3'
down_revision: Union[str, Sequence[str], None] = '0be4d6715397'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reminders', sa.Column('timezone', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('reminders', 'timezone')
    # ### end Alembic commands ###
